services:
  database:
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=esportiva_db
    ports:
      - 5432:5432
volumes:
  pgdata:
